// <auto-generated />
using System;
using MedicalClinic.Infrastructure.MedicalClinic.Infrastructure.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MedicalClinic.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240420173439_InitialIMigrationIdentity")]
    partial class InitialIMigrationIdentity
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MedicalClinic.Domain.Entities.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AppointmentId")
                        .HasComment("Unique identifier for each medical appointment");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime")
                        .HasComment("The date of Appointment");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime")
                        .HasComment("The date when the record  was logically deleted from the system");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int")
                        .HasColumnName("DoctorId")
                        .HasComment("Foreign key referencing the unique identifier of the doctor associated with the appointment");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit")
                        .HasColumnName("IsEnabled ")
                        .HasComment("Indicates if the record  is currently active in the system");

                    b.Property<string>("Observation")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasComment("Additional observation or notes related to the appointment");

                    b.Property<int>("PatientId")
                        .HasColumnType("int")
                        .HasColumnName("PatientId")
                        .HasComment("Foreign key referencing the unique identifier of the patient associated with the appointment");

                    b.Property<int?>("RequestingDoctorId")
                        .HasColumnType("int")
                        .HasColumnName("RequestingDoctorId")
                        .HasComment("Foreign key of the doctor who requested the consultation, if there is a request within the clinic itself");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint")
                        .HasComment("Indicates the Status of the Query, being:\r\n0:Scheduled\r\n1:Confirmed\r\n2: Cancelled\r\n3: Completed");

                    b.HasKey("Id");

                    b.HasIndex("RequestingDoctorId");

                    b.HasIndex(new[] { "DoctorId" }, "IX_Appointments_DoctorId");

                    b.HasIndex(new[] { "PatientId" }, "IX_Appointments_Patientid");

                    b.ToTable("Appointments");

                    b.HasComment("Stores information about medical appointments or consultations");
                });

            modelBuilder.Entity("MedicalClinic.Domain.Entities.Availability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AvailabilityId")
                        .HasComment("Unique identifier for each availability entry.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int")
                        .HasComment("The day of the week when the doctor is available:\r\n0: Monday\r\n1: Tuesday\r\n2: Wednesday\r\n3: Thursday\r\n4: Friday\r\n5: Saturday\r\n6: Sunday");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime")
                        .HasComment("The date when the record  was logically deleted from the system");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int")
                        .HasComment("Foreign key referencing the doctor associated with this availability");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time")
                        .HasComment("The end time of the doctors availability for the specified day");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit")
                        .HasColumnName("IsEnabled")
                        .HasComment("Indicates if the record  is currently active in the system");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time")
                        .HasComment("The start time of the doctors availability for the specified day.");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "DoctorId" }, "IX_Availability_DoctorId");

                    b.ToTable("Availabilities", (string)null);

                    b.HasComment("Stores information about the availability schedule for doctors.");
                });

            modelBuilder.Entity("MedicalClinic.Domain.Entities.CanceledAppointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CanceledAppointmentId")
                        .HasComment("Unique identifier for each canceled appointment");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AppointmentId")
                        .HasColumnType("int")
                        .HasColumnName("AppointmentId")
                        .HasComment("Unique identifier for  appointment");

                    b.Property<DateTime>("CancellationDate")
                        .HasColumnType("datetime")
                        .HasColumnName("CancellationDate")
                        .HasComment("Date when the appointment was canceled");

                    b.Property<string>("ReasonCancellation")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("ReasonCancellation")
                        .HasComment("Reason for the cancellation of the appointment");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "AppointmentId" }, "UK_CanceledAppointment_AppointmentId")
                        .IsUnique();

                    b.ToTable("CanceledAppointment");

                    b.HasComment("Table tracks canceled medical appointments, capturing details such as appointment and cancellation dates");
                });

            modelBuilder.Entity("MedicalClinic.Domain.Entities.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DoctorId")
                        .HasComment("Unique identifier for each doctor in the system");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AddressLineOne")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasComment("The address of the doctor");

                    b.Property<string>("AddressLineTwo")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasComment("The address of the doctor");

                    b.Property<string>("Crm")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasComment("The CRM (Conselho Regional de Medicina) number of the doctor");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime")
                        .HasComment("The date when the record  was logically deleted from the system");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasComment("The email address of the doctor.");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasComment("The first name of the doctor.");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit")
                        .HasColumnName("IsEnabled ")
                        .HasComment("Indicates if the record  is currently active in the system");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasComment(" The last name or surname of the doctor");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasComment("The phone number of the doctor.");

                    b.Property<int>("SpecialtyId")
                        .HasColumnType("int")
                        .HasComment("Unique identifier for each medical specialty");

                    b.HasKey("Id");

                    b.HasIndex("SpecialtyId");

                    b.HasIndex(new[] { "Crm", "DeletedAt" }, "UK_Doctor_Crm_DeletedAt")
                        .IsUnique()
                        .HasFilter("[DeletedAt] IS NOT NULL");

                    b.ToTable("Doctors");

                    b.HasComment("Stores information about medical doctors, their specialties, and contact details.");
                });

            modelBuilder.Entity("MedicalClinic.Domain.Entities.Exam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ExamId")
                        .HasComment("Unique identifier for each medical exam");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime")
                        .HasComment("The date when the record  was logically deleted from the system");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasComment("Description of the exam");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit")
                        .HasColumnName("IsEnabled ")
                        .HasComment("Indicates if the record  is currently active in the system");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasComment("The name of the exam");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,6)")
                        .HasComment("The Value of Exam");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Name", "DeletedAt" }, "UK_Exam_Name_DeletedAt")
                        .IsUnique()
                        .HasFilter("[DeletedAt] IS NOT NULL");

                    b.ToTable("Exams");
                });

            modelBuilder.Entity("MedicalClinic.Domain.Entities.Forwarding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ForwardingId")
                        .HasComment("A unique identifier for each medical record forwarding activity.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Observation")
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("Observation")
                        .HasComment("A field used to store observations or notes related to the fowarding.");

                    b.Property<int>("PrescriptionId")
                        .HasColumnType("int")
                        .HasColumnName("PrescriptionId")
                        .HasComment("An identifier that associates this Fowarding with a specific prescription. It establishes a relationship between Fowardings and the prescriptions in which they are prescribed.");

                    b.Property<int>("SpecialtyId")
                        .HasColumnType("int")
                        .HasColumnName("SpecialtyId")
                        .HasComment("FK of SPecialty");

                    b.HasKey("Id");

                    b.HasIndex("PrescriptionId");

                    b.HasIndex("SpecialtyId");

                    b.ToTable("Forwardings");

                    b.HasComment("The table is structured to capture details about medical referrals, linking them to specific prescriptions, associating them with medical specialties, and providing space for additional observations or notes.");
                });

            modelBuilder.Entity("MedicalClinic.Domain.Entities.Insurance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("InsuranceId")
                        .HasComment("nique identifier for each health insurance plan");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime")
                        .HasComment("The date when the record  was logically deleted from the system");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasComment("Description of the health insurance plan");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit")
                        .HasColumnName("IsEnabled ")
                        .HasComment("Indicates if the record  is currently active in the system");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasComment("The name of the health insurance plan");

                    b.Property<decimal>("PercentageTypeOne")
                        .HasColumnType("decimal(18,6)")
                        .HasComment("A percentage value related to the health insurance plan");

                    b.Property<decimal>("PercentageTypeThree")
                        .HasColumnType("decimal(18,6)")
                        .HasComment("Another percentage value related to the health insurance plan");

                    b.Property<decimal>("PercentageTypeTwo")
                        .HasColumnType("decimal(18,6)")
                        .HasComment("Another percentage value related to the health insurance plan");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Name", "DeletedAt" }, "UK_Insurance_Name_DeletedAt")
                        .IsUnique()
                        .HasFilter("[DeletedAt] IS NOT NULL");

                    b.ToTable("Insurances", (string)null);

                    b.HasComment("Stores information about health insurance plans or medical health plans");
                });

            modelBuilder.Entity("MedicalClinic.Domain.Entities.Medication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MedicationId")
                        .HasComment("A unique identifier for each medication, allowing for easy reference and linkage to prescriptions.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Instruction")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Instruction")
                        .HasComment("Instructions related to the medication. This field provides guidance on how the medication should be taken, including dosage, frequency, and any additional directions");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Name")
                        .HasComment("The name of the medication being prescribed.");

                    b.Property<int>("PrescriptionId")
                        .HasColumnType("int")
                        .HasColumnName("PrescriptionId")
                        .HasComment("An identifier that associates this medication with a specific prescription. It establishes a relationship between medications and the prescriptions in which they are prescribed.");

                    b.Property<string>("SubstituteOne")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("SubstituteOne")
                        .HasComment(" field used to record the name of the first substitute medication, if applicable");

                    b.Property<string>("SubstituteTwo")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("SubstituteTwo")
                        .HasComment("A field used to record the name of the second substitute medication, if applicable.");

                    b.HasKey("Id");

                    b.HasIndex("PrescriptionId");

                    b.ToTable("Medications");

                    b.HasComment("The table is structured to facilitate the management and tracking of prescribed medications, including details about potential substitutes and specific usage instructions.");
                });

            modelBuilder.Entity("MedicalClinic.Domain.Entities.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PatientId")
                        .HasComment("Patients table unique identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AddressLineOne")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasComment("The address line one of the patient.");

                    b.Property<string>("AddressLineTwo")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasComment("The address line two of the patient.");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime")
                        .HasColumnName("DateOfBirth ")
                        .HasComment("The date of birth of the patient");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime")
                        .HasComment("The date when the record  was logically deleted from the system");

                    b.Property<string>("Document")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasComment("Document of Patient");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasComment("The email address of the patient.");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasComment("The  name of the patient");

                    b.Property<byte>("Gender")
                        .HasColumnType("tinyint")
                        .HasComment("The gender of the patient\r\n0: Male, \r\n1: Female,\r\n2: NonBinary");

                    b.Property<int?>("InsuranceId")
                        .HasColumnType("int")
                        .HasComment("Foreign key referencing the unique identifier of the insurance plan associated with the procedure");

                    b.Property<byte?>("InsuranceType")
                        .HasColumnType("tinyint")
                        .HasComment("Type of Insurance");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit")
                        .HasColumnName("IsEnabled ")
                        .HasComment("Indicates if the record  is currently active in the system");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasComment("The last name  of the patient");

                    b.Property<string>("PhoneOne")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasComment("The phone one  number of the patient.");

                    b.Property<string>("PhoneTwo")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasComment("The phone two  number of the patient.");

                    b.HasKey("Id");

                    b.HasIndex("InsuranceId");

                    b.HasIndex(new[] { "Document", "DeletedAt" }, "UK_Patient_Document_DeletedAt")
                        .IsUnique()
                        .HasFilter("[Document] IS NOT NULL AND [DeletedAt] IS NOT NULL");

                    b.ToTable("Patients");

                    b.HasComment("Stores information about patients and their medical records.");
                });

            modelBuilder.Entity("MedicalClinic.Domain.Entities.Prescription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PrescriptionId")
                        .HasComment("A unique identifier for each prescription.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AppointmentId")
                        .HasColumnType("int")
                        .HasColumnName("AppointmentId")
                        .HasComment("An identifier that associates this prescription with a specific appointment or medical visit.");

                    b.Property<string>("Observation")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("Observation")
                        .HasComment("A field used to store observations or notes related to the prescription.");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "AppointmentId" }, "UK_Prescription_AppointmentId")
                        .IsUnique();

                    b.ToTable("Prescriptions");

                    b.HasComment("This table is structured to capture details about medical prescriptions, associating them with specific patients and doctors, recording the date of issuance and expiration, and providing space for any additional notes or instructions associated with the prescription.");
                });

            modelBuilder.Entity("MedicalClinic.Domain.Entities.Procedure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ProcedureId")
                        .HasComment("Unique identifier for each medical procedure");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime")
                        .HasComment("The date when the record  was logically deleted from the system");

                    b.Property<int>("ExamId")
                        .HasColumnType("int")
                        .HasComment("Foreign key referencing the unique identifier of the exam associated with the procedure");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit")
                        .HasColumnName("IsEnabled ")
                        .HasComment("Indicates if the record  is currently active in the system");

                    b.Property<string>("Observation")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasComment("Additional observation or notes related to the procedure");

                    b.Property<int>("PatientId")
                        .HasColumnType("int")
                        .HasComment("Foreign key referencing the unique identifier of the patient associated with the procedure");

                    b.Property<DateTime>("ProcedureDate")
                        .HasColumnType("datetime")
                        .HasComment("The date of Procedure");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint")
                        .HasComment("Indicates the Status of the Procedure, being:\r\n0:Scheduled\r\n1:Confirmed\r\n2: Cancelled\r\n3: Completed");

                    b.Property<int>("TechnicianId")
                        .HasColumnType("int")
                        .HasComment("Foreign key referencing the unique identifier of the technician performing the procedure");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ExamId" }, "IX_Procedures_ExamId");

                    b.HasIndex(new[] { "PatientId" }, "IX_Procedures_PatientId");

                    b.HasIndex(new[] { "TechnicianId" }, "IX_Procedures_TechnicianId");

                    b.HasIndex(new[] { "ProcedureDate" }, "UK_Procedures_ProcedureDate")
                        .IsUnique();

                    b.ToTable("Procedures");

                    b.HasComment("Stores information about medical procedures and exams performed on patients");
                });

            modelBuilder.Entity("MedicalClinic.Domain.Entities.Specialty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SpecialtyId")
                        .HasComment("Unique identifier for each medical specialty");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AppointmentDuration")
                        .HasColumnType("int")
                        .HasColumnName("AppointmentDuration")
                        .HasComment("Standard duration in minutes of the average consultation time for the referring doctor");

                    b.Property<decimal>("ConsultationValue")
                        .HasColumnType("decimal(18,6)")
                        .HasComment("Value of Consultation ");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime")
                        .HasComment("The date when the record  was logically deleted from the system");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasComment("escription of the medical specialty");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit")
                        .HasColumnName("IsEnabled ")
                        .HasComment("Indicates if the record  is currently active in the system");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .IsUnicode(false)
                        .HasColumnType("varchar(60)")
                        .HasComment("The name of the medical specialty");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Name", "DeletedAt" }, "UK_Speciality_Name_DeletedAt")
                        .IsUnique()
                        .HasFilter("[DeletedAt] IS NOT NULL");

                    b.ToTable("Specialties");

                    b.HasComment("Stores information about medical specialties");
                });

            modelBuilder.Entity("MedicalClinic.Domain.Entities.Technician", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TechnicianId")
                        .HasComment("Unique identifier for each Technician");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AddressLineOne")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasComment("The address line one  of the patient.");

                    b.Property<string>("AddressLineTwo")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasComment("The address line two of the patient.");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime")
                        .HasComment("The date when the record  was logically deleted from the system");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasComment("The email address of the technician");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasComment("The first name of the technician");

                    b.Property<byte?>("InsuranceType")
                        .HasColumnType("tinyint")
                        .HasComment("Type of Insurance");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit")
                        .HasColumnName("IsEnabled ")
                        .HasComment("Indicates if the record  is currently active in the system");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasComment("The last name or surname of the technician");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasComment("The phone number of the technician");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "FirstName", "LastName" }, "UK_Technicians_FirstName_LastName")
                        .IsUnique();

                    b.ToTable("Technicians");

                    b.HasComment("Stores information about technicians or technical staff");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MedicalClinic.Domain.Entities.Appointment", b =>
                {
                    b.HasOne("MedicalClinic.Domain.Entities.Doctor", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorId")
                        .IsRequired()
                        .HasConstraintName("FK_Appointments_Doctors");

                    b.HasOne("MedicalClinic.Domain.Entities.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .IsRequired()
                        .HasConstraintName("FK_Appointments_Patients");

                    b.HasOne("MedicalClinic.Domain.Entities.Doctor", "RequestingDoctor")
                        .WithMany("AppointmentsRequestingDoctor")
                        .HasForeignKey("RequestingDoctorId")
                        .HasConstraintName("FK_Appointments_Requesting_Doctor");

                    b.Navigation("Doctor");

                    b.Navigation("Patient");

                    b.Navigation("RequestingDoctor");
                });

            modelBuilder.Entity("MedicalClinic.Domain.Entities.Availability", b =>
                {
                    b.HasOne("MedicalClinic.Domain.Entities.Doctor", "Doctor")
                        .WithMany("Availabilities")
                        .HasForeignKey("DoctorId")
                        .IsRequired()
                        .HasConstraintName("FK_Availability_Doctors");

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("MedicalClinic.Domain.Entities.CanceledAppointment", b =>
                {
                    b.HasOne("MedicalClinic.Domain.Entities.Appointment", "Appointment")
                        .WithMany("CanceledAppointments")
                        .HasForeignKey("AppointmentId")
                        .IsRequired()
                        .HasConstraintName("FK_CanceledAppointments_Specialties");

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("MedicalClinic.Domain.Entities.Doctor", b =>
                {
                    b.HasOne("MedicalClinic.Domain.Entities.Specialty", "Specialty")
                        .WithMany("Doctors")
                        .HasForeignKey("SpecialtyId")
                        .IsRequired()
                        .HasConstraintName("FK_Doctors_Specialties");

                    b.Navigation("Specialty");
                });

            modelBuilder.Entity("MedicalClinic.Domain.Entities.Forwarding", b =>
                {
                    b.HasOne("MedicalClinic.Domain.Entities.Prescription", "Prescription")
                        .WithMany("Forwardings")
                        .HasForeignKey("PrescriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Forwarding_Prescriptions");

                    b.HasOne("MedicalClinic.Domain.Entities.Specialty", "Specialty")
                        .WithMany("Forwardings")
                        .HasForeignKey("SpecialtyId")
                        .IsRequired()
                        .HasConstraintName("FK_Forwarding_Specialties");

                    b.Navigation("Prescription");

                    b.Navigation("Specialty");
                });

            modelBuilder.Entity("MedicalClinic.Domain.Entities.Medication", b =>
                {
                    b.HasOne("MedicalClinic.Domain.Entities.Prescription", "Prescription")
                        .WithMany("Medications")
                        .HasForeignKey("PrescriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Medication_Prescriptions");

                    b.Navigation("Prescription");
                });

            modelBuilder.Entity("MedicalClinic.Domain.Entities.Patient", b =>
                {
                    b.HasOne("MedicalClinic.Domain.Entities.Insurance", "Insurance")
                        .WithMany("Patients")
                        .HasForeignKey("InsuranceId")
                        .HasConstraintName("FK_Patients_Insurance");

                    b.Navigation("Insurance");
                });

            modelBuilder.Entity("MedicalClinic.Domain.Entities.Prescription", b =>
                {
                    b.HasOne("MedicalClinic.Domain.Entities.Appointment", "Appointment")
                        .WithMany("Prescriptions")
                        .HasForeignKey("AppointmentId")
                        .IsRequired()
                        .HasConstraintName("FK_Prescription_Appointments");

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("MedicalClinic.Domain.Entities.Procedure", b =>
                {
                    b.HasOne("MedicalClinic.Domain.Entities.Exam", "Exam")
                        .WithMany("Procedures")
                        .HasForeignKey("ExamId")
                        .IsRequired()
                        .HasConstraintName("FK_Procedures_Exams");

                    b.HasOne("MedicalClinic.Domain.Entities.Patient", "Patient")
                        .WithMany("Procedures")
                        .HasForeignKey("PatientId")
                        .IsRequired()
                        .HasConstraintName("FK_Procedures_Patients");

                    b.HasOne("MedicalClinic.Domain.Entities.Technician", "Technician")
                        .WithMany("Procedures")
                        .HasForeignKey("TechnicianId")
                        .IsRequired()
                        .HasConstraintName("FK_Procedures_Technicians");

                    b.Navigation("Exam");

                    b.Navigation("Patient");

                    b.Navigation("Technician");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MedicalClinic.Domain.Entities.Appointment", b =>
                {
                    b.Navigation("CanceledAppointments");

                    b.Navigation("Prescriptions");
                });

            modelBuilder.Entity("MedicalClinic.Domain.Entities.Doctor", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("AppointmentsRequestingDoctor");

                    b.Navigation("Availabilities");
                });

            modelBuilder.Entity("MedicalClinic.Domain.Entities.Exam", b =>
                {
                    b.Navigation("Procedures");
                });

            modelBuilder.Entity("MedicalClinic.Domain.Entities.Insurance", b =>
                {
                    b.Navigation("Patients");
                });

            modelBuilder.Entity("MedicalClinic.Domain.Entities.Patient", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Procedures");
                });

            modelBuilder.Entity("MedicalClinic.Domain.Entities.Prescription", b =>
                {
                    b.Navigation("Forwardings");

                    b.Navigation("Medications");
                });

            modelBuilder.Entity("MedicalClinic.Domain.Entities.Specialty", b =>
                {
                    b.Navigation("Doctors");

                    b.Navigation("Forwardings");
                });

            modelBuilder.Entity("MedicalClinic.Domain.Entities.Technician", b =>
                {
                    b.Navigation("Procedures");
                });
#pragma warning restore 612, 618
        }
    }
}
